updated workflow to capture invalid suppression file logic

diff --git a/.github/workflows/auto-suppress-CVEs.yml b/.github/workflows/auto-suppress-CVEs.yml
--- a/.github/workflows/auto-suppress-CVEs.yml
+++ b/.github/workflows/auto-suppress-CVEs.yml
@@ -1,6 +1,9 @@
 name: Auto-suppress CVEs
 
 on:
+  push:
+    branches:
+      - patch-fix-auto-suppress-cve-dp
   schedule:
     # At 12 midnight and every 3rd hour from 10am through 11pm
     - cron: "0 0,10-23/3 * * *"
@@ -22,8 +25,8 @@ jobs:
           ref: master
 
       - name: Run yarn audit
-        run: yarn npm audit --recursive --environment production --json > yarn-audit-known-issues || true
-        # continue-on-error: true
+        #run: yarn npm audit --recursive --environment production --json > yarn-audit-known-issues || true
+        run: echo "Injecting an error to test workflow logic: YYN0035: Bad Request" > yarn-audit-known-issues
 
       - name: Check if working directory has changes
         id: check_git_changes
@@ -34,8 +37,19 @@ jobs:
             echo "has_changes=false" >> $GITHUB_OUTPUT
           fi
 
+      - name: Check if added lines contain Yarn errors
+        id: check_yarn_errors
+        run: |
+          added="$(git diff | grep '^+' | sed 's/^\+//')"
+          clean_added="$(echo "$added" | sed 's/\x1b\[[0-9;]*m//g')"
+          if echo "$clean_added" | grep -q 'YYN0035: Bad Request'; then
+            echo "has_yarn_errors=true" >> $GITHUB_OUTPUT
+          else
+            echo "has_yarn_errors=false" >> $GITHUB_OUTPUT
+          fi
+
       - name: Commit suppressed CVEs if there are changes
-        if: steps.check_git_changes.outputs.has_changes == 'true'
+        if: steps.check_git_changes.outputs.has_changes == 'true' && steps.check_yarn_errors.outputs.has_yarn_errors == 'false'
         uses: stefanzweifel/git-auto-commit-action@v4
         with:
           commit_message: Auto-suppress CVEs
